### ISSUE TITLE
Trivial questions - forget about them

### ISSUE THREAD

**Issue by rubencu** [Arquisoft/Trivial_i2a#8]
I think there's no need to waste our time writing questions for the trivial. We should focus on the documentation. If I write 5-6 questions I don't see the point on adding more. Just do your best to write a good documentation as it is as important as the code.

However, we should add a task to add some diagrams generated with Visual Paradigm. What do you think?

**Comment by adanasw** [comment]
I think that doing some views with Visual Paradigm would be nice. Just only the neccessary ones, that describe well the architecture. I can do some of them tomorrow.
